language: python
python:
  - "3.6"
# command to run tests
install:
  - pip install termcolor
  - pip install coveralls
  - pip install coverage
script: 
  - coverage run -m unittest
after_success:
  - coveralls
