language: python
python:
  - "3.6"
# command to run tests
install:
  - pip install termcolor
  - pip install coveralls
script: 
  - coverage run -m unittest
after_success:
  - COVERALLS_REPO_TOKEN=zm8Bi2PgyrTmardGCYbmmRDBCFpgPz8ee coveralls
